language: android
android:
  components:
    - tools
    - platform-tools
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28

before_install:
 - chmod +x gradlew